name: Terraform EC2 Deployment
on:
  push:
    branches:
      - master
jobs:
  plan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan

      - name: Review Plan
        run: terraform show tfplan

      - name: Upload Plan as Artifacts
        uses: actions/upload-artifact@v3

  apply:
    runs-on: ubuntu-latest
    needs: [plan,review]
    environment: Reviewer
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Plan as Artifacts
        uses: actions/download-artifact@v3
        
      - name: Deploy EC2 Instance
        run: terraform apply -auto-approve tfplan

#      - name: Show Outputs
#        run: terraform show